// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: example/example.proto

package example

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExtraServiceClient is the client API for ExtraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtraServiceClient interface {
	Extra(ctx context.Context, in *ExtraRequest, opts ...grpc.CallOption) (*ExtraResponse, error)
}

type extraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtraServiceClient(cc grpc.ClientConnInterface) ExtraServiceClient {
	return &extraServiceClient{cc}
}

func (c *extraServiceClient) Extra(ctx context.Context, in *ExtraRequest, opts ...grpc.CallOption) (*ExtraResponse, error) {
	out := new(ExtraResponse)
	err := c.cc.Invoke(ctx, "/example.ExtraService/Extra", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtraServiceServer is the server API for ExtraService service.
// All implementations must embed UnimplementedExtraServiceServer
// for forward compatibility
type ExtraServiceServer interface {
	Extra(context.Context, *ExtraRequest) (*ExtraResponse, error)
	mustEmbedUnimplementedExtraServiceServer()
}

// UnimplementedExtraServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExtraServiceServer struct {
}

func (UnimplementedExtraServiceServer) Extra(context.Context, *ExtraRequest) (*ExtraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Extra not implemented")
}
func (UnimplementedExtraServiceServer) mustEmbedUnimplementedExtraServiceServer() {}

// UnsafeExtraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtraServiceServer will
// result in compilation errors.
type UnsafeExtraServiceServer interface {
	mustEmbedUnimplementedExtraServiceServer()
}

func RegisterExtraServiceServer(s grpc.ServiceRegistrar, srv ExtraServiceServer) {
	s.RegisterService(&ExtraService_ServiceDesc, srv)
}

func _ExtraService_Extra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtraServiceServer).Extra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ExtraService/Extra",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtraServiceServer).Extra(ctx, req.(*ExtraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtraService_ServiceDesc is the grpc.ServiceDesc for ExtraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.ExtraService",
	HandlerType: (*ExtraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Extra",
			Handler:    _ExtraService_Extra_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/example.proto",
}
